services:
  ut4masterserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
  ut4masterserver-web:
    build:
      dockerfile: .docker/Development.Dockerfile
